version: '3.5'
services:
  traefik:
    image: traefik
    command:
      - "--api.dashboard=false"
      - "--entrypoints.web.address=:80"
      #activation du mode swarm de trafic :
      - "--providers.docker.swarmmode=true"
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      #======================
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker_swarm/docker/traefik/log:/log
    networks:
      - traefik
networks:
  traefik:
    name: traefik
    external: true