---
- hosts : all
  become: true
  tasks:

    - name: Add_directory_bricks
      file:
        dest: "/var/glusterfs/no-direct-write-here/docker/brick1"
        state: directory
    - name: Add_directory_mountpoint
      file:
        dest: "/srv/docker_swarm"
        state: directory
      ignore_errors: true

    - name: Install_gluster
      dnf:
        name: glusterfs-server
        state: present
    - name: Activate_gluster
      service:
        name: glusterd
        state: started
        enabled: true
    - name: Firewall
      shell:
        cmd: "firewall-cmd --zone=public --add-service=glusterfs --permanent"
    - name: Reload_firewall
      shell:
        cmd: "firewall-cmd --reload"

    - name: Create_pool
      gluster.gluster.gluster_peer:
        state: present
        nodes: "{{ gluster_nodes }}"
      ignore_errors: true
      run_once: true

    - name: Tempo_5
      shell:
        cmd: "sleep 10"
    - name: Create gluster volume
      gluster.gluster.gluster_volume:
        state: present
        name: docker
        bricks: /var/glusterfs/no-direct-write-here/docker/brick1
        # rebalance: true
        replicas: "{{ replicas }}"
        cluster: "{{ gluster_nodes }}"
        force: true
      run_once: true
      ignore_errors: true

    - name: Mount_point
      mount:
        src: localhost:/docker
        path: /srv/docker_swarm
        fstype: glusterfs
        opts: defaults,_netdev,noauto,x-systemd.automount
        state: mounted
    - name: Add.autofs.d
      file:
        dest: "/etc/systemd/system/glusterfs.mount.d"
        state: directory
